export const MOCK_COUPONS = [
  {
    id: 1,
    name: '열린 시즌 할인 쿠폰',
    product: '열린',
    designer: '이순신',
    discount: 20,
    isActive: true,
    category: '1차',
    secondaryProduct: '',
    expiryDate: '2024-12-31',
  },
  {
    id: 2,
    name: '신규 고객 환영 쿠폰',
    product: '닫힌',
    designer: '김철수',
    discount: 15,
    isActive: true,
    category: '2차',
    secondaryProduct: '옵션1',
    expiryDate: '2024-11-30',
  },
  {
    id: 3,
    name: '여름 시즌 특가 쿠폰',
    product: '반열린',
    designer: '박영희',
    discount: 25,
    isActive: false,
    category: '1차',
    secondaryProduct: '옵션2',
    expiryDate: '2024-08-31',
  },
  {
    id: 4,
    name: 'VIP 고객 전용 쿠폰',
    product: '열린',
    designer: '최민수',
    discount: 30,
    isActive: true,
    category: '3차',
    secondaryProduct: '옵션3',
    expiryDate: '2024-12-15',
  },
  {
    id: 5,
    name: '연말 감사 쿠폰',
    product: '닫힌',
    designer: '이순신',
    discount: 10,
    isActive: true,
    category: '2차',
    secondaryProduct: '',
    expiryDate: '2024-12-31',
  },
  {
    id: 6,
    name: '봄맞이 특별 쿠폰',
    product: '열린',
    designer: '정민호',
    discount: 18,
    isActive: true,
    category: '1차',
    secondaryProduct: '옵션4',
    expiryDate: '2025-03-31',
  },
  {
    id: 7,
    name: '가을 단풍 쿠폰',
    product: '반열린',
    designer: '김영수',
    discount: 22,
    isActive: false,
    category: '2차',
    secondaryProduct: '',
    expiryDate: '2024-10-31',
  },
  {
    id: 8,
    name: '겨울 따뜻함 쿠폰',
    product: '닫힌',
    designer: '박지은',
    discount: 35,
    isActive: true,
    category: '3차',
    secondaryProduct: '옵션5',
    expiryDate: '2025-02-28',
  },
  {
    id: 9,
    name: '주말 특가 쿠폰',
    product: '열린',
    designer: '최영희',
    discount: 12,
    isActive: true,
    category: '1차',
    secondaryProduct: '옵션6',
    expiryDate: '2025-01-15',
  },
  {
    id: 10,
    name: '평일 할인 쿠폰',
    product: '반열린',
    designer: '이민수',
    discount: 8,
    isActive: false,
    category: '2차',
    secondaryProduct: '',
    expiryDate: '2024-12-20',
  },
  {
    id: 11,
    name: '첫 구매 축하 쿠폰',
    product: '닫힌',
    designer: '김철수',
    discount: 40,
    isActive: true,
    category: '3차',
    secondaryProduct: '옵션7',
    expiryDate: '2025-06-30',
  },
  {
    id: 12,
    name: '재구매 감사 쿠폰',
    product: '열린',
    designer: '박영희',
    discount: 16,
    isActive: true,
    category: '1차',
    secondaryProduct: '옵션8',
    expiryDate: '2025-04-30',
  },
  {
    id: 13,
    name: '생일 축하 쿠폰',
    product: '반열린',
    designer: '정민호',
    discount: 28,
    isActive: false,
    category: '2차',
    secondaryProduct: '',
    expiryDate: '2024-11-15',
  },
  {
    id: 14,
    name: '기념일 특별 쿠폰',
    product: '닫힌',
    designer: '최민수',
    discount: 33,
    isActive: true,
    category: '3차',
    secondaryProduct: '옵션9',
    expiryDate: '2025-05-31',
  },
  {
    id: 15,
    name: '한정판 쿠폰',
    product: '열린',
    designer: '김영수',
    discount: 45,
    isActive: true,
    category: '1차',
    secondaryProduct: '옵션10',
    expiryDate: '2025-01-31',
  },
  {
    id: 16,
    name: '얼리버드 쿠폰',
    product: '반열린',
    designer: '박지은',
    discount: 14,
    isActive: false,
    category: '2차',
    secondaryProduct: '',
    expiryDate: '2024-12-10',
  },
  {
    id: 17,
    name: '마지막 기회 쿠폰',
    product: '닫힌',
    designer: '최영희',
    discount: 50,
    isActive: true,
    category: '3차',
    secondaryProduct: '옵션11',
    expiryDate: '2025-07-31',
  },
  {
    id: 18,
    name: '친구 추천 쿠폰',
    product: '열린',
    designer: '이민수',
    discount: 20,
    isActive: true,
    category: '1차',
    secondaryProduct: '옵션12',
    expiryDate: '2025-03-15',
  },
  {
    id: 19,
    name: '소셜 미디어 쿠폰',
    product: '반열린',
    designer: '이순신',
    discount: 11,
    isActive: false,
    category: '2차',
    secondaryProduct: '',
    expiryDate: '2024-11-25',
  },
  {
    id: 20,
    name: '앱 다운로드 쿠폰',
    product: '닫힌',
    designer: '김철수',
    discount: 25,
    isActive: true,
    category: '3차',
    secondaryProduct: '옵션13',
    expiryDate: '2025-08-31',
  },
  {
    id: 21,
    name: '리뷰 작성 쿠폰',
    product: '열린',
    designer: '박영희',
    discount: 13,
    isActive: true,
    category: '1차',
    secondaryProduct: '옵션14',
    expiryDate: '2025-02-15',
  },
  {
    id: 22,
    name: '뉴스레터 구독 쿠폰',
    product: '반열린',
    designer: '정민호',
    discount: 17,
    isActive: false,
    category: '2차',
    secondaryProduct: '',
    expiryDate: '2024-12-05',
  },
];

export const MOCK_CAMPAIGNS = [
  {
    id: 1,
    name: '여름 시즌 프로모션',
    startDate: '2025-06-01',
    endDate: '2025-08-31',
    status: 'scheduled',
    description: '여름 시즌 특별 할인 캠페인',
    targetAudience: 'all',
    couponId: 1,
  },
  {
    id: 2,
    name: '신규 고객 환영 캠페인',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'active',
    description: '신규 가입 고객 대상 웰컴 캠페인',
    targetAudience: 'new',
    couponId: 2,
  },
  {
    id: 3,
    name: '연말 감사 이벤트',
    startDate: '2024-12-01',
    endDate: '2024-12-31',
    status: 'completed',
    description: '연말 고객 감사 이벤트',
    targetAudience: 'vip',
    couponId: 5,
  },
  {
    id: 4,
    name: 'VIP 고객 전용 캠페인',
    startDate: '2025-03-01',
    endDate: '2025-05-31',
    status: 'scheduled',
    description: 'VIP 등급 고객 대상 특별 혜택',
    targetAudience: 'vip',
    couponId: 4,
  },
  {
    id: 5,
    name: '봄맞이 리뉴얼 캠페인',
    startDate: '2025-03-15',
    endDate: '2025-04-30',
    status: 'draft',
    description: '봄 시즌 메뉴 리뉴얼 홍보',
    targetAudience: 'all',
    couponId: 6,
  },
  {
    id: 6,
    name: '겨울 따뜻함 캠페인',
    startDate: '2024-12-01',
    endDate: '2025-02-28',
    status: 'active',
    description: '겨울 시즌 따뜻한 메뉴 프로모션',
    targetAudience: 'all',
    couponId: 8,
  },
  {
    id: 7,
    name: '가을 단풍 축제',
    startDate: '2024-09-01',
    endDate: '2024-11-30',
    status: 'completed',
    description: '가을 시즌 테마 캠페인',
    targetAudience: 'all',
    couponId: 7,
  },
  {
    id: 8,
    name: '학생 할인 캠페인',
    startDate: '2025-02-01',
    endDate: '2025-04-30',
    status: 'active',
    description: '학생 대상 특별 할인 혜택',
    targetAudience: 'student',
    couponId: 9,
  },
  {
    id: 9,
    name: '직장인 점심 특가',
    startDate: '2025-01-15',
    endDate: '2025-06-15',
    status: 'active',
    description: '직장인 점심시간 특별 메뉴',
    targetAudience: 'office',
    couponId: 10,
  },
  {
    id: 10,
    name: '주말 가족 캠페인',
    startDate: '2024-11-01',
    endDate: '2025-01-31',
    status: 'active',
    description: '주말 가족 단위 고객 대상',
    targetAudience: 'family',
    couponId: 11,
  },
  {
    id: 11,
    name: '생일 축하 이벤트',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'active',
    description: '생일 고객 대상 특별 혜택',
    targetAudience: 'birthday',
    couponId: 13,
  },
  {
    id: 12,
    name: '첫 방문 고객 환영',
    startDate: '2025-02-01',
    endDate: '2025-07-31',
    status: 'scheduled',
    description: '첫 방문 고객 대상 웰컴 이벤트',
    targetAudience: 'new',
    couponId: 12,
  },
  {
    id: 13,
    name: '재방문 감사 캠페인',
    startDate: '2024-10-01',
    endDate: '2024-12-31',
    status: 'completed',
    description: '재방문 고객 감사 이벤트',
    targetAudience: 'returning',
    couponId: 21,
  },
  {
    id: 14,
    name: '소셜 미디어 이벤트',
    startDate: '2025-03-01',
    endDate: '2025-05-31',
    status: 'draft',
    description: 'SNS 팔로우 고객 대상 이벤트',
    targetAudience: 'social',
    couponId: 19,
  },
  {
    id: 15,
    name: '앱 다운로드 캠페인',
    startDate: '2025-01-01',
    endDate: '2025-03-31',
    status: 'active',
    description: '모바일 앱 다운로드 유도 캠페인',
    targetAudience: 'mobile',
    couponId: 20,
  },
  {
    id: 16,
    name: '리뷰 작성 이벤트',
    startDate: '2024-12-15',
    endDate: '2025-02-15',
    status: 'active',
    description: '리뷰 작성 고객 대상 혜택',
    targetAudience: 'reviewer',
    couponId: 21,
  },
  {
    id: 17,
    name: '친구 추천 캠페인',
    startDate: '2025-04-01',
    endDate: '2025-06-30',
    status: 'scheduled',
    description: '친구 추천 시 양쪽 모두 혜택',
    targetAudience: 'referral',
    couponId: 18,
  },
  {
    id: 18,
    name: '멤버십 업그레이드',
    startDate: '2025-02-15',
    endDate: '2025-04-15',
    status: 'draft',
    description: '멤버십 등급 업그레이드 유도',
    targetAudience: 'member',
    couponId: 14,
  },
  {
    id: 19,
    name: '시즌 메뉴 출시',
    startDate: '2024-11-15',
    endDate: '2025-01-15',
    status: 'completed',
    description: '신규 시즌 메뉴 홍보 캠페인',
    targetAudience: 'all',
    couponId: 15,
  },
  {
    id: 20,
    name: '매장 확장 기념',
    startDate: '2025-05-01',
    endDate: '2025-07-31',
    status: 'scheduled',
    description: '신규 매장 오픈 기념 이벤트',
    targetAudience: 'local',
    couponId: 17,
  },
  {
    id: 21,
    name: '고객 만족도 조사',
    startDate: '2025-03-15',
    endDate: '2025-04-15',
    status: 'draft',
    description: '고객 만족도 조사 참여 이벤트',
    targetAudience: 'survey',
    couponId: 16,
  },
  {
    id: 22,
    name: '브랜드 런칭 기념',
    startDate: '2024-08-01',
    endDate: '2024-10-31',
    status: 'completed',
    description: '브랜드 런칭 1주년 기념 이벤트',
    targetAudience: 'all',
    couponId: 22,
  },
  {
    id: 23,
    name: '환경보호 캠페인',
    startDate: '2025-04-22',
    endDate: '2025-06-22',
    status: 'scheduled',
    description: '지구의 날 기념 환경보호 캠페인',
    targetAudience: 'eco',
    couponId: 3,
  },
  {
    id: 24,
    name: '건강한 식단 프로모션',
    startDate: '2025-01-01',
    endDate: '2025-03-31',
    status: 'active',
    description: '신년 건강한 식단 프로모션',
    targetAudience: 'health',
    couponId: 1,
  },
];

export const MOCK_WORKFLOWS = [
  {
    id: 1,
    name: '신규 가입 환영 시퀀스',
    description: '첫방문 고객에게 30일 후 헤어컷 쿠폰을 발송합니다.',
    isActive: true,
    status: 'published',
    author: {
      name: '김마케팅',
      department: '마케팅팀',
    },
    trigger: {
      type: 'customer-behavior',
      label: '회원가입 완료',
    },
    action: {
      type: 'message-coupon',
      label: '환영 메시지 + 10% 쿠폰',
    },
    tags: ['신규고객', '환영'],
    stats: {
      affected: 1247,
      triggered: 89,
    },
    lastTriggered: '2024-01-15T10:30:00Z',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 2,
    name: '이탈 리마인드',
    description: '신규로 이탈 위험 태그가 붙은 고객에게 메세지와 쿠폰 발송.',
    isActive: true,
    status: 'published',
    author: {
      name: '박세일즈',
      department: '영업팀',
    },
    trigger: {
      type: 'time-based',
      label: '이탈 위험 태그 붙은 날',
    },
    action: {
      type: 'message',
      label: '구매 완료 독려 메시지',
    },
    tags: ['장바구니', '리타겟팅'],
    stats: {
      affected: 3421,
      triggered: 156,
    },
    lastTriggered: '2024-01-14T15:45:00Z',
    createdAt: '2024-01-05T00:00:00Z',
  },
  {
    id: 3,
    name: 'VIP 고객 특별 혜택',
    description: 'VIP 등급 고객에게 월간 특별 쿠폰을 자동으로 제공합니다.',
    isActive: false,
    status: 'published',
    author: {
      name: '이고객',
      department: 'CRM팀',
    },
    trigger: {
      type: 'segment-based',
      label: 'VIP 등급 고객',
    },
    action: {
      type: 'coupon',
      label: 'VIP 전용 20% 쿠폰',
    },
    tags: ['VIP', '월간혜택'],
    stats: {
      affected: 89,
      triggered: 12,
    },
    lastTriggered: '2024-01-01T09:00:00Z',
    createdAt: '2023-12-15T00:00:00Z',
  },
  {
    id: 4,
    name: '생일 축하 캠페인',
    description: '고객의 생일에 맞춰 개인화된 축하 메시지와 특별 할인을 제공합니다.',
    isActive: true,
    status: 'draft',
    author: {
      name: '정이벤트',
      department: '마케팅팀',
    },
    trigger: {
      type: 'time-based',
      label: '고객 생일',
    },
    action: {
      type: 'message-coupon',
      label: '생일 축하 메시지 + 15% 쿠폰',
    },
    tags: ['생일', '개인화'],
    stats: {
      affected: 0,
      triggered: 0,
    },
    lastTriggered: null,
    createdAt: '2024-01-10T00:00:00Z',
  },
  // 페이지네이션 테스트를 위한 추가 데이터
  ...Array.from({ length: 20 }, (_, i) => ({
    id: i + 5,
    name: `테스트 워크플로우 ${i + 1}`,
    description: `테스트용 워크플로우 설명 ${i + 1}`,
    isActive: i % 2 === 0,
    status: i % 3 === 0 ? 'draft' : 'published',
    author: {
      name: `테스터${i + 1}`,
      department: '테스트팀',
    },
    trigger: {
      type: ['customer-behavior', 'time-based', 'segment-based'][i % 3],
      label: `테스트 트리거 ${i + 1}`,
    },
    action: {
      type: 'message',
      label: `테스트 액션 ${i + 1}`,
    },
    tags: [`테스트${i + 1}`, '자동화'],
    stats: {
      affected: Math.floor(Math.random() * 1000),
      triggered: Math.floor(Math.random() * 100),
    },
    lastTriggered: i % 4 === 0 ? null : '2024-01-10T00:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
  })),
];
